### ISSUE TITLE
Quick Question about RGF baseline

### ISSUE THREAD

**Issue by inkawhich** [thu-ml/Prior-Guided-RGF#6]
To get the RGF results in the paper, do you just run P-RGF with lambda=0? Is it as simple as that, or is there something else I am missing?

Thanks in advance.

**Comment by csy530216** [comment]
Hello, sorry for the late reply.

According to Eq. (10) in the [paper](https://arxiv.org/pdf/1906.06919.pdf), in fact RGF corresponds to P-RGF with lambda=1/D (then C=1/D times the identity matrix), where D=`image_size * image_size * 3` in the code. But in the code, we get the RGF (`FLAGS.method == 'uniform'`) results without running P-RGF (`FLAGS.method == 'biased'`). You can set `FLAGS.method` to `'uniform'` and follow the logic in the code.

Let me know if you have other questions.

**Comment by inkawhich** [comment]
Thanks!
