### ISSUE TITLE
The meaning of Equation A.3

### ISSUE THREAD

**Issue by yuhaoooo** [thu-ml/Prior-Guided-RGF#7]
Thanks for this insteresting work. I have some questions when reading your paper.

Here is an equtaion in your appendix A.4. However, I cannot understant how to get it.
![dmeo](https://user-images.githubusercontent.com/24415219/104125575-a85e1200-5392-11eb-8146-bd23798d9088.png)
Can you explain this to me? Thanks a lot!

**Comment by csy530216** [comment]
Hello! The first equality is mainly because E[X^2]=E[(X-E[X])^2]+E[X]^2. The second equality is mainly because when the sequence of random variables X_1, X_2, ..., X_n are i.i.d., we have Var( (X_1 + X_2 + ... + X_n) / n) = 1/n Var(X_1).
Let me know if you still have questions.
